### ISSUE TITLE
Transactions aren't going though.

### ISSUE THREAD

**Issue by blunt8112** [spaceboundbot/solana-sniper-bot#6]
[07:47:09.840] DEBUG: Signature 5zN4hMkjoSSwVtzgZwDF3ToKxCTAdrovCHNbnQFdgG2rZkubxLMUGQpJzpEUp1xwNm4DoCKWhbFaiBu15BvMM2NT has expired: block height exceeded.
    err: {
      "type": "TransactionExpiredBlockheightExceededError",
      "message": "Signature 5zN4hMkjoSSwVtzgZwDF3ToKxCTAdrovCHNbnQFdgG2rZkubxLMUGQpJzpEUp1xwNm4DoCKWhbFaiBu15BvMM2NT has expired: block height exceeded.",
      "stack":
          TransactionExpiredBlockheightExceededError: Signature 5zN4hMkjoSSwVtzgZwDF3ToKxCTAdrovCHNbnQFdgG2rZkubxLMUGQpJzpEUp1xwNm4DoCKWhbFaiBu15BvMM2NT has expired: block height exceeded.
              at Connection.confirmTransactionUsingBlockHeightExceedanceStrategy (C:\Users\Administrator\Desktop\solana-sniper-bot-main\node_modules\@solana\web3.js\src\connection.ts:3957:15)
              at processTicksAndRejections (node:internal/process/task_queues:95:5)
              at async Connection.confirmTransaction (C:\Users\Administrator\Desktop\solana-sniper-bot-main\node_modules\@solana\web3.js\src\connection.ts:3768:14)
      "signature": "5zN4hMkjoSSwVtzgZwDF3ToKxCTAdrovCHNbnQFdgG2rZkubxLMUGQpJzpEUp1xwNm4DoCKWhbFaiBu15BvMM2NT"
![capturemint](https://github.com/spaceboundbot/solana-sniper-bot/assets/163455794/4b6f302f-0754-449d-81bb-9ab5e7dcd6da)

**Comment by solcasey** [comment]
1. try a different rpc https://www.helius.dev/ for example
2. you don't have enough sol

**Comment by blunt8112** [comment]
I have enough sol. It will be good if u guys can add a feature where we can customize gas fees  + slippage

**Comment by blunt8112** [comment]
& which Solana RPC/websocket connection is better ? Not talking about node.

**Comment by blunt8112** [comment]
and this is helius.dev
